require("adam.options")
require("adam.keymaps")
require("adam.plugins")
require("adam.colorscheme")
require("adam.cmp")
require("adam.lsp")
require("adam.telescope")
require("adam.treesitter")
require("adam.autopairs")
require("adam.comment")

